### ISSUE TITLE
placeAtTop prop should be removed.

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/react-responsive-audio-player#12]
Since default fixed positioning [has been removed](https://github.com/benwiley4000/react-responsive-audio-player/issues/6) the `placeAtTop` prop to the component should also be removed. This entails:

* Remove `placeAtTop` from `AudioPlayer.propTypes`
* Remove relevant annotation from above `AudioPlayer` class definition
* Remove conditional application of `top` class to `.audio_player` element
* Remove `.audio_player.top` rules from index.scss
* Remove any mention of `placeAtTop` from README.md

**Comment by MarkReeder** [comment]
I can take this on within the next day or two.

**Comment by benwiley4000** [comment]
Thanks Mark, appreciate the help.

**Comment by benwiley4000** [comment]
Thanks, Mark, I appreciate the help.
