### ISSUE TITLE
How I can change active song in playlist?

### ISSUE THREAD

**Issue by romanlex** [benwiley4000/react-responsive-audio-player#143]
Hello
How I can change active song in playlist?
I can sort playlist array again and again, but I think what right way create api for this functional

**Comment by benwiley4000** [comment]
@romanlex, thanks for asking! The short answer is that in version 1 you cannot do this - it doesn't really make sense to specify the current song declaratively when this information should be able to change for other natural reasons (user interaction, previous track ending).

For what you need, one hack you can try currently is to specify a playlist with only one track at a time. You can change the prop to include your new track when desired, and use the audio element ref to call .play() afterward to make sure playback continues. There's more discussion in #65.

Note that in version 2 (coming soon, and in progress on the `next` branch) you'll be able to specify custom control components that can receive callback props to update audio state from any part of the UI. This is probably what you want, I think.

One case I haven't really considered is where you want your audio to be remotely controllable by another device (e.g. how Spotify works with multiple devices). I'm open to suggestions on how to do this. It's possible with the new API (create a custom control component that subscribes to a WebSocket and calls callback props on data update). However this might be considered awkward to some folks.

**Comment by romanlex** [comment]
big thx for the answer, i'm waiting version 2.0 for this)

**Comment by benwiley4000** [comment]
Cool! I'll leave the issue open until v2 lands.

**Comment by benwiley4000** [comment]
@romanlex 

Hey again - as I mentioned this feature is already accessible via the `next` branch. As for the other related feature I mentioned, which would be remote control of the current track in the playlist, there's not yet a first-class API for that, although development of that feature is now being tracked in #203, which probably won't land in v2.0 as it's somewhat complex.

HOWEVER, if you know the url of the track you want to switch to, in v2.0 you'll be able to use the `audioElementRef` to set `element.src` to whatever you want. We'll actually intercept the request to update the src, make sure it exists in the playlist, then update the UI to match. :slightly_smiling_face: 

That said, I'll close out this issue for now. Let me know if you have other questions and sorry for the extended delay.

**Comment by benwiley4000** [comment]
I'm hoping to have a v2.0 alpha out in the next several days.

**Comment by joelrojo** [comment]
Any eta on the release of v2.0? 

I'm trying to use the `next` branch in my development but can't seem to get it to work. Added `"react-responsive-audio-player": "benwiley4000/react-responsive-audio-player#next",` to my `package.json` under `dependencies` and am now getting the error:

`Module not found: Can't resolve 'react-responsive-audio-player'`

Wanting to update the playlist based on what users click on in my app. It loads correctly but I'm trying to programmatically autoplay the src rather than having them have to click the play button again. So I tried the method you mentioned of `audioElementRef` and `play()`, but that didn't update the UI or play correctly, so not I'm trying to use `element.src` and update to the `next` branch. Here's my code:

```javascript
componentDidUpdate(prevProps, prevState) {
  if (prevProps.audiolog) {
    if (prevProps.audiolog.mediaUrl !== this.props.audiolog.mediaUrl) {
      this.audioElement.src = this.props.audiolog.mediaUrl;
    }
  }
}
```

and 

```javascript
<AudioPlayer
  playlist={playlist}
  autoplay={true}
  controls={['spacer', 'playpause', 'spacer', 'progress']}
  audioElementRef={elem => this.audioElement = elem }
/>
```

Any suggestions would be much appreciated. Really great package btw, thanks for your hard work!

**Comment by benwiley4000** [comment]
Hey @joelrojo the new version is out in alpha and uses multiple packages. You can install them with:

```
npm install @cassette/core@2.0.0-alpha.2 @cassette/player@2.0.0-alpha.2
```

(`@cassette/core` is a peer dependency for `@cassette/player`). I haven't actually tested the fresh install workflow yet so it's possible something is broken. Or maybe it works!

The API has changed a bit and I'm still trying to get it documented. I'm hoping today or tomorrow you should be able to follow the documentation to use it. In the meantime you can check the example app to follow along.

For your usage you should be able to do:

```jsx
import { MediaPlayer } from '@cassette/player';

// ...

<MediaPlayer
  playlist={playlist}
  autoplay={true}
  controls={['spacer', 'playpause', 'spacer', 'progress']}
  mediaElementRef={elem => this.audioElement = elem }
/>
```

The "more correct" way would involve creating a PlayerContextProvider (from the `@cassette/core` package) and calling the passed-down function to change the track when you need to. But I think the above should work for you and solve your immediate needs.

As for your question: I don't think the UI will update correctly in version 1 so you're probably going to want to upgrade to version 2, like you said. Sorry things are a bit behind.

**Comment by benwiley4000** [comment]
BTW if you have custom CSS styles they won't continue working in the new version. All the styles and html structure were completely changed.

**Comment by benwiley4000** [comment]
And here's the live demo page for the new player. https://benwiley4000.github.io/react-responsive-audio-player/example.html

**Comment by joelrojo** [comment]
Thanks for this, very helpful! Only thing is the fresh install doesn't seem to work. Tried it and now am getting a module not found error: `Module not found: Can't resolve '@cassette/player'`

Do you have any resources for implementing it with PlayerContextProvider instead? Not a huge rush so I can just wait for your release of documentation if that's easier. Thanks again!

**Comment by benwiley4000** [comment]
@joelrojo here's an incomplete but in-progress API documentation: https://benwiley4000.github.io/react-responsive-audio-player/styleguide/

No examples, props that are shared between components are only defined on one of them, etc.

As for the install issue... not sure why the install didn't work. I can try to test it later today when I'm off work. Can you show me the structure of your `node_modules/@cassette/player` directory after the install?

**Comment by benwiley4000** [comment]
Make sure you are using the named import instead of default import since version 2 doesn't have default exports.

**Comment by joelrojo** [comment]
awesome, I'll look into the documentation. I tried named import instead of default to no avail. Here is the directory structure:

<img width="314" alt="screen shot 2018-10-05 at 10 17 13 am" src="https://user-images.githubusercontent.com/217719/46549759-f157bf80-c887-11e8-95d8-50696fde7425.png">

**Comment by benwiley4000** [comment]
Hey, I can just do this one quickly.

**Comment by joelrojo** [comment]
awesome, thanks! Lmk when it's good to go and I'll test it out.

**Comment by benwiley4000** [comment]
It's ready now - you can upgrade your dependencies to `2.0.0-alpha.3`.

**Comment by joelrojo** [comment]
@benwiley4000 it works! thank you. Just had to add a direct link to the css to make sure the styles applied. Final code:

``` javascript
import '@cassette/player/dist/css/cassette-player.css'

  componentDidUpdate(prevProps, prevState) {
    if (prevProps.audiolog) {
      if (prevProps.audiolog.mediaUrl !== this.props.audiolog.mediaUrl) {
        this.audioElement.src = this.props.audiolog.mediaUrl;
        this.audioElement.play();
      }
    }
  }
```

**Comment by benwiley4000** [comment]
Awesome! Glad it worked. :)

**Comment by benwiley4000** [comment]
P.S. is calling the play() method necessary? Just curious.. I thought it wasn't anymore.

**Comment by joelrojo** [comment]
When I didn't call play() it would update the src but pause playback, requiring the user to hit  the play button again.

I'm loading the playlist with a button outside of this component, which might be the issue and why I have to hack it this way.

I'm assuming I'll be able to fix this doing it the "right" way with the PlayerContext in the 2.0 release. But for now it works well!

**Comment by benwiley4000** [comment]
Does your updated playlist have any media sources in common with the previous one?

**Comment by joelrojo** [comment]
No, I'm basically just creating a playlist with one track and replacing that track through `props` everytime a user clicks on a custom audiolog component:

`const playlist =[{ url: this.props.audiolog.mediaUrl, title: this.props.audiolog.title }]`

**Comment by joelrojo** [comment]
@benwiley4000 thanks for the tips, all super helpful! This player is a crucial component of what I'm building and I really appreciate you putting it together.

**Comment by benwiley4000** [comment]
@joelrojo I'm glad to hear that. If you're interested I can ping you when more docs are ready.

**Comment by joelrojo** [comment]
@benwiley4000 Yea that'd be great, thanks!
