### ISSUE TITLE
Backskip, Forwardskip do not work correctly

### ISSUE THREAD

**Issue by Mixddux** [benwiley4000/react-responsive-audio-player#144]
Hi. 

TLDR; the skip buttons function like 'backskip'. 

I made a track list and when the player starts, all good on track one. Then I hit either backskip or forwardskip and the play selects the last song. Subsequent clicks to either track backwards up the playlist.

**Comment by benwiley4000** [comment]
@Mixddux you're totally right - my mistake! I just merged a fix into master.

**Comment by benwiley4000** [comment]
This is tagged as v1.2.1 and pushed to master but I'm having weird issues trying to publish to npm right now...

**Comment by benwiley4000** [comment]
@Mixddux  v1.2.1 is now published - can you update the dependency and see if it does what you need? thanks! :slightly_smiling_face:
