### ISSUE TITLE
Pull Sass values out into variables

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/react-responsive-audio-player#16]
In order to support easier visual configuration, Sass values that would commonly be overridden should be stored at the top of [index.scss](https://github.com/benwiley4000/react-responsive-audio-player/blob/master/src/index.scss) as variables. These values would include (but not be limited to) "magic" numbers and values which are particularly opinionated.

Please see react-gif-player's [GifPlayer.scss](https://github.com/benwiley4000/react-gif-player/blob/master/src/GifPlayer.scss) for a good example of what this can look like.

Each variable should use the `!default` flag so that it can be preempted if a user has already defined it in another Sass sheet. E.g.

```scss
$audio_player_bg_color: #333 !default;
```

There's not strictly a right or wrong way to do this. 

Variables should be `snake_cased` and begin with `$audio_player_`.

**Comment by Anichale** [comment]
Hi benwiley4000, I'll try take a stab at this.

**Comment by benwiley4000** [comment]
Thanks!

**Comment by benwiley4000** [comment]
Addressed by #17.
