### ISSUE TITLE
Programmatically play audio

### ISSUE THREAD

**Issue by pablopaul** [benwiley4000/react-responsive-audio-player#2]
I am trying to `play()` the audio from a wrapping component.

I am including the AudioPlayer like this 
```
<AudioPlayer playlist={playlist} hideBackSkip={true} ref="audioPlayer" />
```

Then in the wrapping component I try to play the audio inside `componentDidMount()`
```
componentDidMount() {
  this.refs.audioPlayer.audio.play();
}
```

The audio is only playing automatically **after the first user interaction** (i.e. button click) – Do you know why?

I saw the "autoplay" prop and want to start `play()` programmatically to make it work in mobile safari.

**Comment by benwiley4000** [comment]
I was going to ask - then saw at the end of your message - you're using Mobile Safari. Autoplay before user interaction is disabled in Mobile Safari unfortunately! It seems to work in most other browsers, though (let me know if you discover the same issue in other browsers). I'm going to close this for now.

**Comment by benwiley4000** [comment]
If you have any way of accessing Mobile Safari's JavaScript console you should see a warning message letting you know that audio playback tried and failed. [See here](https://github.com/benwiley4000/react-responsive-audio-player/blob/master/src/index.js#L166).

**Comment by benwiley4000** [comment]
One other comment - if autoplay is allowed in your browser, you shouldn't need to reach into the `AudioPlayer` component to tell the audio element to play. Setting the `autoplay` prop to `true` accomplishes precisely the same effect (using a timeout, but by default the timeout's delay is 0 milliseconds).

**Comment by pablopaul** [comment]
@benwiley4000 Also on desktop chrome the audio plays only after my first click – any idea why?

**Comment by benwiley4000** [comment]
Not sure. It works fine for me in Chrome 47 for Linux.

Try this link - does it play automatically? http://benwiley4000.github.io/react-responsive-audio-player/

If it does work, you might want to check out the source for that example, [here](https://github.com/benwiley4000/react-responsive-audio-player/tree/gh-pages).
