### ISSUE TITLE
A volume bar would be amazing.

### ISSUE THREAD

**Issue by RageMaster14** [benwiley4000/react-responsive-audio-player#30]
I love the player and I tried a variation of it but It seems yours is missing the basic volume bar

**Comment by benwiley4000** [comment]
Hey @RageMaster14, thanks for flagging. It seems like this might be the same request as issue #1. Could we move discussion there? I'd love to hear what you're looking for this in this kind of feature.

**Comment by benwiley4000** [comment]
I've written a proposal for something related in #1. If you have any further thoughts (which I hope you do!), please respond there. 😄
