### ISSUE TITLE
Timestamp rounds up to nearest second, MediaStatusBar momentarily reads :60

### ISSUE THREAD

**Issue by abrahamian** [benwiley4000/react-responsive-audio-player#428]
You can reproduce this bug simply by playing a track in the live style guide. When the playback time is between 59.5 and 60, the timestamp in the `MediaStatusBar` displays `:60`

<img width="903" alt="Screen Shot 2019-06-27 at 3 49 34 PM" src="https://user-images.githubusercontent.com/5331128/60296081-4e524480-98f3-11e9-9f5e-3c4742bee30f.png">

The problem lies in the [`convertToTime`](https://github.com/benwiley4000/cassette/blob/next/packages/player/src/utils/convertToTime.js#L7) function, which rounds _up_ to the nearest second. It should instead round _down_, so that the number displayed represents elapsed seconds.

- between 0 and 1 second past the minute, it should show `:00`
- between 59 and 60 seconds past the minute, it should show `:59`

**Comment by benwiley4000** [comment]
@abrahamian I checked a few random players online (Vimeo, YouTube, Bandcamp) and indeed it seems the behavior you're suggesting is standard. Thanks for flagging this problem! I'd be happy to take a pull request if you'd like to work on it.

**Comment by benwiley4000** [comment]
Ah, just realized you already left one! Thanks! :)
