### ISSUE TITLE
Dynamically change track via props

### ISSUE THREAD

**Issue by Makhlab** [benwiley4000/react-responsive-audio-player#65]
What about change current audio track through props?

**Comment by Makhlab** [comment]
I'm apologies. Having **audioElementRef** and **playlist** props should be enough to change dynamically a track and trigger play fn.

**Comment by benwiley4000** [comment]
Hm... yeah, that should be workable! Currently, it's what I would recommend. I would generally say to use the `playlist` prop to change what's playing from outside, though that might seem like a lot of work if all you wanted to do was move to the next track in a playlist that was already loaded.

For the moment I'm hesitant to use props to convey temporal events (which become invalid after an update even though the prop is still there).

Though I am hoping you can tell me about your use case. Does your song selection/navigation happen externally, and you're just using this component for play/pause and name display? Or is it something else?

Note that in the upcoming 2.0 release you'll be able to create totally custom child control components with access to callbacks passed down from `AudioPlayer` for triggering actions like changing tracks, volume, seek position, etc. Perhaps this would be useful to you! See #42, and the [2.0 milestone](https://github.com/benwiley4000/react-responsive-audio-player/milestone/2).

**Comment by benwiley4000** [comment]
@Makhlab would you be able to talk about what you're using this for?

**Comment by Makhlab** [comment]
@benwiley4000  I wanted to integrated it into our website (podcast / radio). But we need an ability to programmatically set index of a track of playlist to be played. 

1. Update the playlist
2. Set track index
3. Play

Probably there's a quick way to hack the existing code, huh?

**Comment by benwiley4000** [comment]
With version 2 there will be a starting track index prop - the playlist
will begin at the index you specify. Is that good?

**Comment by benwiley4000** [comment]
It is available already in the next branch.

**Comment by Makhlab** [comment]
I very much appreciate it. 

`<AudioPlayer playlist={podcast} startingTrackIndex={0} />`

**Comment by benwiley4000** [comment]
If you have trouble with that please let me know!

**Comment by benwiley4000** [comment]
Also possibly relevant is the `onActiveTrackChange` callback prop which we'll be including with 2.0. #70

**Comment by benwiley4000** [comment]
@Makhlab as far as I'm concerned this isn't resolved - I'd like to find a solution.

In general, it **is** possible to remotely affect other audio properties, like volume, muted, playbackRate, paused - you just set them on the audio element, and the UI updates. This is important especially for scenarios like an OS-level audio control (e.g. on Android) that pops up while audio is playing - if a user uses those controls, our UI needs to stay in sync.

The only attribute we're not really tracking is `src`, and the reason I've put that off is that I'm not totally sure what should happen if we don't find the new `src` url in our loaded playlist. But either way it's possible for the user to remotely change the `src`, so we should probably cover the cases we can. This would solve your problem, I'd guess.

**Comment by benwiley4000** [comment]
@Makhlab I went ahead and merged a fix into the `next` branch. You can now directly change `audio.src` to the url matching the track you need to play.

One more feature blocking the 2.0 release may be a superior solution, though - we'll be providing a [`withAudioPlayer` higher-order-component](https://github.com/benwiley4000/react-responsive-audio-player/issues/109) which will let you place `AudioPlayer` high up in your component hierarchy and request context props deep down somewhere. I'd imagine this might also solve the issue you were running into.
