### ISSUE TITLE
Better build test recommendations in CONTRIBUTING.md

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/react-responsive-audio-player#7]
The contribution guidelines recommend testing by creating a symbolic link from your local build directory to your `node_modules` directory to test your build in your project (via `ln -s`). This is kind of weird, and the instructions don't apply to Windows systems.

Instead, I think we should probably recommend [installing the package via local path](https://docs.npmjs.com/files/package.json#local-paths).

Before committing, we should ensure this routine works without errors. Other methods (e.g. `npm link`) have been known to cause problems.

**Comment by nistath** [comment]
Is using npm-link a bad idea, or were you thinking of another method?

**Comment by benwiley4000** [comment]
My thought was to recommend installing the package via local path (as shown at the link above).

In the past `npm link` didn't work for me because the linked module would attempt to use its own copy of React. This may not be an issue with npm 3 because `peerDependencies` are no longer downloaded automatically. I'd appreciate some assistance with testing - if you're able, please let me know what exactly you did, what the result was, and what version(s) of npm you're using.

**Comment by nistath** [comment]
Well with 3.10.3 the linking of files works (even in Windows). I don't have time to test it in an actual installation. I'll tell you tomorrow.

**Comment by benwiley4000** [comment]
@nistath any update? I may have time to test this soon but in the meantime I'm curious if you've looked into it.

**Comment by nistath** [comment]
@benwiley4000 I haven't. I'm really busy with my college applications and have practically no time. Sorry. I'll let you know if I do.

**Comment by benwiley4000** [comment]
@nistath understood. I tested `npm link` just now and it appears the problem hasn't been resolved; I get the error `Error: Cannot find module 'react'`. For now, I'd like to recommend installing via local path (as I suggested in the initial issue write-up).

**Comment by benwiley4000** [comment]
I'm currently using the local install routine, and while it works, it's much less convenient than using `ln -s` in that you must manually re-install the module each time it updates. For now, I'm going to stick with the existing testing recommendations.

**Comment by nistath** [comment]
Okay then! Maybe npm isn't the best manager after all, as many have said. :P Good luck!

**Comment by benwiley4000** [comment]
Thanks. I'm going to close this issue for now but should the `npm link` situation improve in the future we'll update the readme.

**Comment by benwiley4000** [comment]
Solved via [example.html](https://github.com/benwiley4000/react-responsive-audio-player/blob/master/example.html).
