### ISSUE TITLE
Webpack css-loader should use css modules

### ISSUE THREAD

**Issue by benwiley4000** [benwiley4000/react-responsive-audio-player#8]
If we use css modules for style loading, class names will be made unique automatically and there will be no need to namespace/nest everything under `.audio_player` (nesting makes style computation slower).

**Comment by m-sureshraj** [comment]
Hi @benwiley4000 
I would like to work on this issue. I already used css modules for couple of my projects, so i can fix this issue.

**Comment by benwiley4000** [comment]
@m-sureshraj if you'd like to submit a pull request please do! Thanks. Keep in mind a few things:

-  the final CSS should continue to be extracted on build as it is now
- please use css-loader's built-in `?module` query param to activate modules - if I'm correct listing css-modules as a dev dependency is unnecessary?
- I would like all child selectors directly under `.audio_player` to be pulled out to the top level. Deeper child classes should stay the way they are.

**Comment by benwiley4000** [comment]
@m-sureshraj This could be annoying if you've begun work on the changes already, but I made several code style updates on the master branch just now. Please pull the latest into your branch. Thanks!

**Comment by m-sureshraj** [comment]
Hi, @benwiley4000 

Sure, I will pull the latest changes to my branch. Thanks :+1:

**Comment by benwiley4000** [comment]
@m-sureshraj I am now realizing that css modules may make it more difficult for users to override default styles - I'm not sure if there's a good way around this and if not we may have to abort the migration to CSS modules. What do you think?

**Comment by benwiley4000** [comment]
I'm going to remove this from the 1.0 target for now. If you're able to find a good solution to the style override problem, feel free to still submit a PR.
